import datetime
import streamlit as st1
import main

st1.image("DOM.png", width=200)
st1.header("Donracks One Stop Storage Solutions")


question = st1.text_input("What's Your Question", 'Enter Text')

if st1.button('Get Answer'):
    answer = main.getopenairesponse("www.donracks.co.in", question)
    #answer = " The answer generated by application wll be displayed hereThe \n answer generated by application wll be displayed hereThe answer generated by application wll be displayed hereThe answer generated by application wll be displayed hereThe answer generated by application wll be displayed hereThe answer generated by application wll be displayed hereThe answer generated by application wll be displayed hereThe answer generated by application wll be displayed here"
    timeanswered = datetime.datetime.now()
    st1.title(f"\n  Your Answer ")
    st1.write(answer)
    st1.write(timeanswered)

if st1.button('Clear'):
    question = ''