import datetime
import streamlit as st2
import main

st2.image("TRU.png", width=300)
st2.header("Trueloader - Data Integration Platform")
question = st2.text_input("What's Your Question", '')

if st2.button('Get Answer'):
    answer = main.getopenairesponse("www.trueloader.com", question)
    #answer = " The answer generated by application wll be displayed hereThe \n answer generated by application wll be displayed hereThe answer generated by application wll be displayed hereThe answer generated by application wll be displayed hereThe answer generated by application wll be displayed hereThe answer generated by application wll be displayed hereThe answer generated by application wll be displayed hereThe answer generated by application wll be displayed here"
    timeanswered = datetime.datetime.now()
    st2.title(f"\n")
    st2.write(answer)
    st2.write(timeanswered)

if st2.button('Clear'):
    question = ''
